/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PaperTradingRouteImport } from './routes/paper-trading'
import { Route as OptionsRouteImport } from './routes/options'
import { Route as NewsRouteImport } from './routes/news'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as IndexRouteImport } from './routes/index'

const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperTradingRoute = PaperTradingRouteImport.update({
  id: '/paper-trading',
  path: '/paper-trading',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsRoute = OptionsRouteImport.update({
  id: '/options',
  path: '/options',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/journal': typeof JournalRoute
  '/news': typeof NewsRoute
  '/options': typeof OptionsRoute
  '/paper-trading': typeof PaperTradingRoute
  '/portfolio': typeof PortfolioRoute
  '/risk': typeof RiskRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/journal': typeof JournalRoute
  '/news': typeof NewsRoute
  '/options': typeof OptionsRoute
  '/paper-trading': typeof PaperTradingRoute
  '/portfolio': typeof PortfolioRoute
  '/risk': typeof RiskRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/journal': typeof JournalRoute
  '/news': typeof NewsRoute
  '/options': typeof OptionsRoute
  '/paper-trading': typeof PaperTradingRoute
  '/portfolio': typeof PortfolioRoute
  '/risk': typeof RiskRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/journal'
    | '/news'
    | '/options'
    | '/paper-trading'
    | '/portfolio'
    | '/risk'
    | '/scanner'
    | '/settings'
    | '/signals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/journal'
    | '/news'
    | '/options'
    | '/paper-trading'
    | '/portfolio'
    | '/risk'
    | '/scanner'
    | '/settings'
    | '/signals'
  id:
    | '__root__'
    | '/'
    | '/journal'
    | '/news'
    | '/options'
    | '/paper-trading'
    | '/portfolio'
    | '/risk'
    | '/scanner'
    | '/settings'
    | '/signals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JournalRoute: typeof JournalRoute
  NewsRoute: typeof NewsRoute
  OptionsRoute: typeof OptionsRoute
  PaperTradingRoute: typeof PaperTradingRoute
  PortfolioRoute: typeof PortfolioRoute
  RiskRoute: typeof RiskRoute
  ScannerRoute: typeof ScannerRoute
  SettingsRoute: typeof SettingsRoute
  SignalsRoute: typeof SignalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper-trading': {
      id: '/paper-trading'
      path: '/paper-trading'
      fullPath: '/paper-trading'
      preLoaderRoute: typeof PaperTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options': {
      id: '/options'
      path: '/options'
      fullPath: '/options'
      preLoaderRoute: typeof OptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JournalRoute: JournalRoute,
  NewsRoute: NewsRoute,
  OptionsRoute: OptionsRoute,
  PaperTradingRoute: PaperTradingRoute,
  PortfolioRoute: PortfolioRoute,
  RiskRoute: RiskRoute,
  ScannerRoute: ScannerRoute,
  SettingsRoute: SettingsRoute,
  SignalsRoute: SignalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
